drop table third_client if exists;
create table third_client (
	id bigint generated by default as identity,
	name varchar(64),
	client_id varchar(32),
	client_secret varchar(64),
	private_key varchar(2048),
	redirect_uri varchar(64),
	scope varchar(256),
	primary key(id)
);

drop table user if exists;
create table user (
	id bigint generated by default as identity,
	account varchar(32),
	password varchar(32),
	name varchar(64),
	age int,
	balance decimal(20,2),
	primary key(id)
);
